=== Json Authentication

Filter 'FacebookAuthJsonFilter' accepts Facebook Access Token or Signed Request as parameter, and responds
 with JSON to authorization requests. It's useful if you an external client for your Grails application, it
 could be Android or iOS application, or Desktop application, or just AJAX client.

[NOTE]
====
JSON filter just returns an object with user details, nothing else. For authentication of other requests,
you still have to use different filter. If you have a RESTful client, take a look at
http://grails.org/plugin/spring-security-oauth2-provider[spring-security-oauth2-provider plugin]
====

How it works:

----
> GET /j_spring_security_facebook_json?access_token=<ACCESS_TOKEN>
----

For successful authorization you'll get:
----
< HTTP/1.1 200 OK
< Content-Type: application/json;charset=UTF-8
<
{
  "authenticated": true,
  "uid": 12345612345,   # Facebook User Id
  "roles":[
     "ROLE_FACEBOOK",
     "ROLE_USER"
  ],
  "username": "facebook_12345612345", # Grails Application User Id/Username
  "enabled": true # Grails Application User status
}
----

For unsuccessful:
----
< HTTP/1.1 401 Unauthorized
< Content-Type: application/json;charset=UTF-8
<
{
  "authenticated": false,
  "message": "Expired token" # Authentication Failure reason
}
----

==== How to extend JSON response

The plugin going to call `Map onJsonSuccess(Map input, FacebookAuthToken token)`
or `Map onJsonFailure(Map input, AuthenticationException exception)` methods
of FacebookAuthService (if exists).

There you can update `input` data with any other values, introduce new fields/keys, or even return your
own structure. This structure will be transformed to JSON and sent to client.
